### PR TITLE
adding .travis.yml

### PR DESCRIPTION
**Pull request by dereklwood**
- [x] adding .travis.yml

### CODE REVIEW

**Comment by dereklwood** [comment]
hmmm, will investigate why this is failing

**Comment by wolf31o2** [comment]
Specs need a stub_command for the transparent defrag check.

**Comment by dereklwood** [comment]
right, but i'm unable to reproduce this locally... strange

**Comment by dereklwood** [comment]
ok i gave in and added the stub to pretty much all other specs.  I also updated `spec_helper.rb` to run them in random order

**Comment by wolf31o2** [comment]
:+1: LGTM

**Pull request merged**
